FROM debian:latest

USER root

RUN apt-get -y update
RUN apt-get -y install git nginx nodejs python3 python3-pip
# /opt
RUN cd /opt
RUN git clone https://github.com/JohannesItten/vmix-monitoring.git
# /opt/vmix-monitoring
RUN cd vmix-monitoring
RUN pip install -r requirements.txt
# /opt/vmix-monitoring/frontend
RUN cd frontend
RUN npm install
RUN npm build

