nrf-2025:
  recording:
    text: REC
    icon: fa fa-hdd-o
  streaming:
    text: STREAM
    icon: fa fa-youtube-play
  master:
    text: M
    icon:
  audiokey:
    text: MIC
    icon: fa fa-volume-up
