standart24:
  recording:
    text: REC
    icon: fa fa-hdd-o
  streaming:
    text: STREAM
    icon: fa fa-youtube-play
  master:
    text: M
    icon:
  ruskey:
    text: RUS
    icon: fa fa-volume-up
  engkey:
    text: ENG
    icon: fa fa-volume-up

standart24-2:
  busA:
    text: A
    icon:
  busB:
    text: B
    icon:
  busC:
    text: C
    icon:
  busD:
    text: D
    icon:
  busE:
    text: E
    icon:
