nrf-2025:
  idle: [zastkey, advkey]
  watch: [audiokey, titlekey]
  online: [
    [streaming, [], error],
    [recording, [], error],
    [/busMuted, [M], error],
    [/inputMuted, [audiokey], error],
    [/busLevelLow, [M, -18, 5], warning]
  ]
  offline: [
    [inputMuted, [audiokey], info]
  ]
  always: [
  ]