test:
  idle: [zastkey, shapkakey]
  watch: [testkey, multikey, audiokey, timelapse]
  buses: [M, A, B]
  online: [
    [external, [], error],
    [streaming, [], warning],
    [fullscreen, [], error],
    [inputBus, [timelapse, MAB], info]
  ]
  offline: [
  ]
  always: [
  ]