test:
  idle: [zastkey, shapkakey]
  watch: [testkey, multikey, audiokey, timelapse]
  buses: [M, A, B]
  online: [
    [inputLevelLow, [timelapse, -18, 10], warning],
    [streaming, [], warning]
  ]
  offline: [
  ]
  always: [
  ]