#rule: skip means do not mon this vmix
vmix-test:
  name: test-vmix
  unit: Adam Savage
  ip: 10.5.1.99
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-blue-1:
  name: Зал 1 (BLUE 1)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-blue-2:
  name: Зал 2 (BLUE 2)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-blue-3:
  name: Зал 3 (BLUE 3)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-blue-4:
  name: Зал 4 (BLUE 4)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-blue-5:
  name: Зал 5 (BLUE 5)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-green-5:
  name: Зал 6 (GREEN 5)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-green-6:
  name: Зал 7 (GREEN 6)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-green-8:
  name: Зал 8 (GREEN 8)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-green-9:
  name: Зал 9 (GREEN 9)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

vmix-green-10:
  name: Зал 10 (GREEN 10)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025

red-8:
  name: Зал 11 (RED 8+9)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025
  
red-10:
  name: Зал 12 (RED 10)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025
  
red-11:
  name: Зал 13 (RED 11)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025
  
lobby:
  name: Зал 14 (lobby)
  unit: Adam Savage
  ip: 127.0.0.2
  port: 8088
  username:
  password:
  rule: nrf-2025