#rule: skip means do not mon this vmix
vmix-testmon:
  name: maintest
  unit: Ivanov
  ip: 192.168.10.254
  port: 8088
  username: admin
  password: 123
  rule: test

vmix-test2:
  name: skiptest
  unit: Sidorov
  ip: 127.0.0.1
  port:
  username:
  password:
  rule:

vmix-test3:
  name: configtest
  unit: kkk
  ip: 192.168.10.255
  port:
  username:
  password:
  rule: